FROM tinygo/tinygo:0.18.0 AS build

RUN groupadd -r ubuntu && useradd -m -r -u 1000 -g ubuntu ubuntu && usermod -aG sudo ubuntu

USER ubuntu

WORKDIR /src

COPY . .

RUN tinygo build -o ./http-trace-filter.wasm -target=wasi src/trace/main.go

FROM scratch AS bin

COPY --from=build /src/http-trace-filter.wasm /
